package pe.edu.unsch.entities;
// Generated 05/07/2019 12:27:33 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Carga generated by hbm2java
 */
@Entity
@Table(name = "carga", catalog = "cargabd")
public class Carga implements java.io.Serializable {

	private int idcarga;
	private Docente docente;
	private Semestre semestre;
	private short horas;
	private Set<CargaCurso> cargaCursos = new HashSet<CargaCurso>(0);
	private String nombre;
	private String apellido;
	private String semestres;

	public Carga() {
	}
	
	public Carga(String nombre, String apellido, String semestres, short hora) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.semestres = semestres;
		this.horas = hora;
	}

	public Carga(int idcarga, Docente docente, Semestre semestre, short horas) {
		this.idcarga = idcarga;
		this.docente = docente;
		this.semestre = semestre;
		this.horas = horas;
	}

	public Carga(int idcarga, Docente docente, Semestre semestre, short horas, Set<CargaCurso> cargaCursos) {
		this.idcarga = idcarga;
		this.docente = docente;
		this.semestre = semestre;
		this.horas = horas;
		this.cargaCursos = cargaCursos;
	}

	@Id

	@Column(name = "idcarga", unique = true, nullable = false)
	public int getIdcarga() {
		return this.idcarga;
	}

	public void setIdcarga(int idcarga) {
		this.idcarga = idcarga;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsemestre", nullable = false)
	public Semestre getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}

	@Column(name = "horas", nullable = false)
	public short getHoras() {
		return this.horas;
	}

	public void setHoras(short horas) {
		this.horas = horas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carga")
	public Set<CargaCurso> getCargaCursos() {
		return this.cargaCursos;
	}

	public void setCargaCursos(Set<CargaCurso> cargaCursos) {
		this.cargaCursos = cargaCursos;
	}

	@Transient
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Transient
	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Transient
	public String getSemestres() {
		return semestres;
	}

	public void setSemestres(String semestres) {
		this.semestres = semestres;
	}
	
	

}
