package pe.edu.unsch.entities;
// Generated 05/07/2019 12:27:33 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private int idsemestre;
	private String nombre;
	private Date anio;
	private Set<Carga> cargas = new HashSet<Carga>(0);

	public Semestre() {
	}

	public Semestre(int idsemestre, String nombre, Date anio) {
		this.idsemestre = idsemestre;
		this.nombre = nombre;
		this.anio = anio;
	}

	public Semestre(int idsemestre, String nombre, Date anio, Set<Carga> cargas) {
		this.idsemestre = idsemestre;
		this.nombre = nombre;
		this.anio = anio;
		this.cargas = cargas;
	}

	@Id

	@Column(name = "idsemestre", unique = true, nullable = false)
	public int getIdsemestre() {
		return this.idsemestre;
	}

	public void setIdsemestre(int idsemestre) {
		this.idsemestre = idsemestre;
	}

	@Column(name = "nombre", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", nullable = false, length = 10)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestre")
	public Set<Carga> getCargas() {
		return this.cargas;
	}

	public void setCargas(Set<Carga> cargas) {
		this.cargas = cargas;
	}

}
